version: 2
jobs:
  build:
    docker:
      - image: circleci/slim-base
    branches:
      ignore:
      - '/slummed\/.*/'
    steps:
      - add-ssh-keys:
          fingerprints:
          - '56:76:54:43:c3:70:31:03:b5:ff:20:89:43:af:a2:48'
      - checkout
      - run:
          name: Create slummed mirror of this branch
          command: |
            if [[ -n "$CIRCLE_BRANCH" ]]; then
              git branch "slummed/$CIRCLE_BRANCH"
              git filter-branch --commit-filter "$PWD/git-slum.sh" "slummed/$CIRCLE_BRANCH"
              git push -f origin "slummed/$CIRCLE_BRANCH"
            fi
